ejemplo1/proyectoUno/administrativo/urls.py
"""
    Manejo de urls para la aplicación
    administrativo
"""
from django.urls import path
# se importa las vistas de la aplicación
from . import views


urlpatterns = [
        path('inicio', views.index, name='index'),
        path('listado-estudiantes', views.listadoEstudiantes, 
            name='listadoEstudiates'),
        path('listado-estudiantes-dos', views.listadoEstudiantesDos, 
            name='listadoEstudiatesDos'),
        path('crear-estudiante', views.crearEstudiante, 
            name='crearEstudiante'),
        path('editar-estudiante/<int:id>', views.editarEstudiante, 
            name='editarEstudiante'),
]

ejemplo1/proyectoUno/proyectoUno/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrativo/', include('administrativo.urls')),
]

ejemplo1/proyectoUno/administrativo/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    cedula = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return "%s %s %s" % (self.nombre, 
                self.apellido,
                self.cedula)

class NumeroTelefonico(models.Model):
    telefono = models.CharField(max_length=100)
    tipo = models.CharField(max_length=100)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.telefono, self.tipo)

ejemplo1/proyectoUno/administrativo/forms.py
from django.forms import ModelForm
from administrativo.models import Estudiante


class EstudianteForm(ModelForm): 
    class Meta:
        model = Estudiante 
        fields = ['nombre', 'apellido', 'cedula'] 

ejemplo1/proyectoUno/administrativo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render

# importar las clases de models.py
from administrativo.models import *

# importar los formularios de forms.py 
from administrativo.forms import *

# Create your views here.

def index(request):
    # return HttpResponse("Hola mundo desde Python")
    return HttpResponse("Hola mundo desde Python<br/>%s" % (request.path))

def listadoEstudiantes(request):
    """
    Listar los registros del modelo Estudiante, 
    obtenidos de la base de datos.
    """
    # a través del ORM de django se obtiene
    # los registros de la entidad; el listado obtenido
    # se lo almacena en una variable llamada
    # estudiantes
    estudiantes = Estudiante.objects.all()
    # en la variable tipo diccionario llamada informacion_template
    # se agregará la información que estará disponible
    # en el template
    informacion_template = {'estudiantes': estudiantes, 'numero_estudiantes': len(estudiantes)}
    return render(request, 'listadoEstudiantes.html', informacion_template)
    

def listadoEstudiantesDos(request):
    """
    Listar los registros del modelo Estudiante, 
    obtenidos de la base de datos.
    """
    estudiantes = Estudiante.objects.all()
    # en la variable tipo diccionario llamada informacion_template
    # se agregará la información que estará disponible
    # en el template
    informacion_template = {'estudiantes': estudiantes, 'numero_estudiantes': len(estudiantes)}
    return render(request, 'listadoEstudiantesDos.html', informacion_template)
 

def crearEstudiante(request):
    """
    """
    if request.method=='POST':
        formulario = EstudianteForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(listadoEstudiantesDos)
    else:
        formulario = EstudianteForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crearEstudiante.html', diccionario) 


def editarEstudiante(request, id):
    """
    """
    estudiante = Estudiante.objects.get(pk=id)
    if request.method=='POST':
        formulario = EstudianteForm(request.POST, instance=estudiante)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(listadoEstudiantesDos)
    else:
        formulario = EstudianteForm(instance=estudiante)
    diccionario = {'formulario': formulario}

    return render(request, 'editarEstudiante.html', diccionario) 

ejemplo1/proyectoUno/administrativo/templates/crearEstudiante.html
<h2>Crear Estudiante</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

ejemplo1/proyectoUno/administrativo/templates/editarEstudiante.html
<h2>Editar Estudiante</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Actualizar'/></p>
</form>

ejemplo1/proyectoUno/administrativo/templates/listadoEstudiantes.html
Número de estudiantes {{ numero_estudiantes }}
<br/>
<br/>

{% for e in estudiantes %}

  {{e}}<br/>

{% endfor %}

ejemplo1/proyectoUno/administrativo/templates/listadoEstudiantesDos.html
{% extends "master.html" %}

{% block title %}
  Listado de Estudiantes
{% endblock %}

{% block content %}

<h2>Listado de Estudiantes</h3>
<h3>Número de estudiantes {{ numero_estudiantes }}</h3>

{% for e in estudiantes %}
    
  {{e}}<br/>
  <ul>
  {% for numero in e.numerotelefonico_set.all%}
      <li>
          Número telefónico {{numero}}<br/>
      </li>
  {% endfor %}
  </ul>
  <br/>
{% endfor %}

{% endblock %}

ejemplo1/proyectoUno/administrativo/templates/master.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    <h1>Aplicación Administración </h1>
    <hr>
      {% block content %}
      {% endblock %}

    <hr>
    <footer>
      <p>Loja-Ecuador</p>
      <p>{% now "jS F Y H:i" %}</p>
    </footer>
  </body>
</html>